version: "3.9"

services:
  backend:
    build:
      context: ./backend
      target: development
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:4000
    command: npm run dev
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/frontend/src/app
      - /frontend/src/app/node_modules
    ports:
      - '3000:3000'
